// AUTOGENERATED CODE on 2026-02-27T17:53:28.362729 - do not edit directly!

use bao1x_api::bio_code_aligned;

#[rustfmt::skip]
bio_code_aligned!(dabao_tester_bio_code, BM_DABAO_TESTER_BIO_START, BM_DABAO_TESTER_BIO_END,
    "20:", // _start: @_start
    // --- inline asm begin ---
    "lui	sp, 1",
    "j	21f",
    // --- inline asm end ---
    "21:", // main: @main
    "lui	a0, 129272",
    "addi	a0, a0, -1986",
    // --- inline asm begin ---
    "mv	x26, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	x25, a0",
    // --- inline asm end ---
    // --- inline asm begin ---
    "mv	a0, x21",
    // --- inline asm end ---
    "22:", // .LBB1_1: =>This Inner Loop Header: Depth=1
    // --- inline asm begin ---
    "mv	a1, x21",
    // --- inline asm end ---
    "beq	a1, a0, 23f",
    // in Loop: Header=BB1_1 Depth=1
    "xor	a0, a0, a1",
    // --- inline asm begin ---
    "mv	x16, a0",
    // --- inline asm end ---
    "23:", // .LBB1_3: in Loop: Header=BB1_1 Depth=1
    // --- inline asm begin ---
    "li	x20, 0",
    // --- inline asm end ---
    "j	22b"
);
